name: Python Tests

on:
  push:
    branches: [ main, dev, staging, feature/* ]
  pull_request:
    branches: [ main, dev, staging ]

jobs:
  python-tests-status:
    name: "Python Tests Status Check"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest